//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportApp {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    public sealed partial class PathSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PathSettings defaultInstance = ((PathSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PathSettings())));
        
        public static PathSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\CTApp\\DB\\Data.sqlite")]
        public string DatabasePath {
            get {
                return ((string)(this["DatabasePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\CTApp\\DB\\Vehicle.sqlite")]
        public string VehicleDatabasePath {
            get {
                return ((string)(this["VehicleDatabasePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\CTApp\\Settings\\Report.xml")]
        public string ReportSettingsPath {
            get {
                return ((string)(this["ReportSettingsPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\CTApp\\DB\\Phone.sqlite")]
        public string PhoneDatabasePath {
            get {
                return ((string)(this["PhoneDatabasePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\CTApp\\Help\\")]
        public string HelpPath {
            get {
                return ((string)(this["HelpPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\CTApp\\Shift Entry Presets\\")]
        public string ShiftEntryPresetLocation {
            get {
                return ((string)(this["ShiftEntryPresetLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("f:\\")]
        public string DefaultSaveLocation {
            get {
                return ((string)(this["DefaultSaveLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\CTApp\\DB\\Other.sqlite")]
        public string OtherDatabasePath {
            get {
                return ((string)(this["OtherDatabasePath"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\CTApp\\Settings\\")]
        public string SettingsLocation {
            get {
                return ((string)(this["SettingsLocation"]));
            }
            set {
                this["SettingsLocation"] = value;
            }
        }
    }
}
